### ISSUE TITLE
[Feature] Enable pip installation without cloning

### ISSUE THREAD

**Issue by rdnfn** [jajimer/sinergym#120]
Firstly, thanks a lot for this awesome package! I am finding it very useful and easy to work with!

**Requested feature:** I was wondering if it would be possible to make this package pip installable without cloning the repo first.

As far as I understand it, right now the only way to install sinergym is to do

```
git clone https://github.com/jajimer/sinergym.git
pip install -e .
```

**Possible solution** (but I may be wrong): Trying to figure out a way to install sinergym in my own workflow without cloning it first, I have noticed that neither installing it in non-editable mode

```
git clone https://github.com/jajimer/sinergym.git
pip install .
```

nor directly from GitHub

```
pip install git+https://github.com/jajimer/sinergym.git
```

work. Although they don't fail in obvious ways (one can't be imported, the other yields an empty package on import). Looking at the package configuration, I think the only thing that is missing may be some arguments in the `setup()` call of the `setup.py` file that add subpackages and modules to the sinergym package (e.g. the `packages` key). The `-e` option only seems to work because it adds the cloned repo to the sys.path, bypassing your setup.py.

I have found this tutorial a quite helpful reference for `setup.py` etc. for my own work:

https://packaging.python.org/en/latest/tutorials/packaging-projects/ 

Thanks a lot for looking into this, and thanks again for publishing this package!

EDIT: clarified what I mean in the `setup.py` file

**Comment by jajimer** [comment]
Hi, @rdnfn. Thank you very much for your comments!

We normally use the Dockerfile to avoid installing Energy+ and setting environment variables by hand, but I guess it is easier to use it with other packages that way. We will go through the tutorial to make it pip installable, thanks!

**Comment by rdnfn** [comment]
Hi @jajimer,

Awesome, thanks for the quick response and looking into this! 

Definitely agree: it's not too important in a docker workflow but it would make it a bit more convenient and straightforward when using sinergym with other packages and in other contexts.

**Comment by AlejandroCN7** [comment]
Hello @rdnfn. Sinergym package is already available without cloning GitHub repository:
`pip install sinergym`
or, if you want extras packages:
`pip install sinergym[extras]`
Thanks!

**Comment by rdnfn** [comment]
That's absolutely awesome, thanks a lot for implementing this!
