### ISSUE TITLE
[Feature]: Dynamic reward based on occupation

### ISSUE THREAD

**Issue by manjavacas** [jajimer/sinergym#155]
### Feature 🚀

Let's consider the possibility of adjusting comfort weight in the reward function depending on the level of occupancy.

### Motivation

As comfort requirements can be relaxed when there are no people inside a building, it would be interesting to dynamically change reward's comfort weight (i.e. importance) in these situations.

### Additional information

An interesting paper related to occupancy and HVAC control is the following:

> Barrett, E., & Linder, S. (2015, September). Autonomous HVAC control, a reinforcement learning approach. In Joint European conference on machine learning and knowledge discovery in databases (pp. 3-19). Springer, Cham.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/jajimer/sinergym/issues) in the repo (**required**)

:pencil: Please, don't forget to include more labels besides `Feature Request` if it is necessary.

**Comment by jajimer** [comment]
See #152 and #151, as this feature may be included there.

**Comment by jajimer** [comment]
Closed with #152
