### ISSUE TITLE
[BUG]: Unregistered error for data center  and IWM environments. 

### ISSUE THREAD

**Issue by tummalapallimurali** [jajimer/sinergym#163]
### Bug 🐛
Unregistered error for data center environments. 

### To Reproduce

gym.error.UnregisteredEnv: No registered env with id: Eplus-datacenter-discrete-v, Eplus-datacenter-continuous-v1 , Eplus-datacenter-discrete-stochastic-v1 ,  Eplus-datacenter-continuous-stochastic-v1. This is also happening for IWMullion environments.  Other environments work fine. I already included "Import sinergym" in the code.

Steps to reproduce the behavior.

**

**root@58f4215b445a:/workspaces/sinergym# /usr/bin/python /workspaces/sinergym/DRL_battery.py --environment Eplus-IWMullion-discrete-v1  --episodes 1 --algorithm PPO --logger  --tensorboard /Users/Murali/sinergym/tensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gym/envs/registration.py", line 150, in spec
    return self.env_specs[id]
KeyError: 'Eplus-IWMullion-discrete-v1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/sinergym/DRL_battery.py", line 204, in <module>
    env = gym.make(args.environment, reward=LinearReward())
  File "/usr/local/lib/python3.9/dist-packages/gym/envs/registration.py", line 184, in make
    return registry.make(id, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gym/envs/registration.py", line 105, in make
    spec = self.spec(path)
  File "/usr/local/lib/python3.9/dist-packages/gym/envs/registration.py", line 167, in spec
    raise error.UnregisteredEnv("No registered env with id: {}".format(id))
gym.error.UnregisteredEnv: No registered env with id: Eplus-IWMullion-discrete-v1**

**

```python
from sinergym import ...

```

```bash
Traceback (most recent call last): File ...

```

### Expected behavior

I am expecting simulation files to be created with monitor.csv and progress.csv.

### System Info

Describe the characteristic of your environment:
 * Describe how Sinergym was installed (pip, docker, source, ...) : Docker
 * Sinergym Version [e.g. 1.7.3]: 1.7.6
 * OS: [e.g. iOS] : Macintosh
 * Python version [3.9 recommended]: 3.9
 * Gym version
 * Versions of any other relevant libraries

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/jajimer/sinergym/issues) in the repo (**required**)
- [x] I have read the [documentation](https://jajimer.github.io/sinergym/build/html/index.html) (**required**)
- [ ] I have provided a minimal working example to reproduce the bug (**required**)

:pencil: Please, don't forget to include more labels besides `bug` if it is necessary.

**Comment by AlejandroCN7** [comment]
Hi @tummalapallimurali! I think you are using names of environments that do not exist. For example, try the following code for a datacenter simulation (it works):

```python
import gym
import numpy as np
import sinergym

env = gym.make('Eplus-datacenter-hot-discrete-stochastic-v1')
for i in range(1):
    obs = env.reset()
    rewards = []
    done = False
    current_month = 0
    while not done:
        a = env.action_space.sample()
        obs, reward, done, info = env.step(a)
        rewards.append(reward)
        if info['month'] != current_month:  # display results every month
            current_month = info['month']
            print('Reward: ', sum(rewards), info)
    print(
        'Episode ',
        i,
        'Mean reward: ',
        np.mean(rewards),
        'Cumulative reward: ',
        sum(rewards))
env.close()
```
