### ISSUE TITLE
why do i have 3 elements in rcv (Raw information received from Sinergym)?  Resulting error IndexError: list index out of range due to only

### ISSUE THREAD

**Issue by Jaydeemourg** [jajimer/sinergym#205]
### System Info
Sinergym Version 1.8.1
OS: Ubuntu 18.04
Python version 3.9
Gym version 0.23.1

### what i have done
I have placed the idf and epw files in the building and weather folders of sinergym respectively. moreso, i have created a variables.cfg and observations and actions space for my particular building. i could also run the sinergym example was run successfully

### Question
I want to create an environment for my specific building idf and epw. upon runnung the try_env.py, i got an error stating that ```IndexError: list index out of range```. 
while debugging, i found out that in the eplus.py file, the rcv (Raw information received from Sinergym) has  only  3 elements 
```['2', '-10', '\n']```, i don't know why this is so. Kindly suggest tips on solving this issue. Thanks in advance

the output of ```rcv_1st = conn.recv(2048).decode(encoding='ISO-8859-1')``` is  2 -10 

output of utilSocket.log:
```utilSocket: Establishing socket based on file socket.cfg.
Getting socket port number.
Received socket port number 47417.
Socket port number = 47417.
Socket opened, sockfd = 16.
Assembling buffer.
Write to socket with fd = 16
Buffer        = 2 -10 

Wrote 7 characters to socket.
sendclientmessage wrote flag -10, return value = 7.
In readbufferfromsocket: Read 0 chars, maximum is 0.
Assembling buffer.
Write to socket with fd = 16
Buffer        =  �d<�2 -1 

Wrote 12 characters to socket.
sendclientmessage wrote flag -1, return value = 12.
In readbufferfromsocket: Read 0 chars, maximum is 0.```

**Comment by jajimer** [comment]
Hi. Could you provide the complete log error?

**Comment by Jaydeemourg** [comment]
@jajimer here is the complete traceback:
![image](https://user-images.githubusercontent.com/64713825/161966713-675698d9-03be-4958-86c2-300c29ef3ea1.png)

**Comment by Jaydeemourg** [comment]
I have solved the issue. i just needed to change the keys for the variable ``` "ZONE THERMAL COMFORT FANGER MODEL PPD" and  "FACILITY TOTAL HVAC ELECTRICITY DEMAND RATE" with key "PERSONENB001" in the idf file```.
