### ISSUE TITLE
[BUG]: Reward penalty and comfort violation metric error?

### ISSUE THREAD

**Issue by AlejandroCN7** [jajimer/sinergym#208]
### Bug 🐛
According to an experiment realized by @manjavacas, the comfort violation rates and reward comfort penalties do not correspond correctly to the internal building temperatures versus the established comfort intervals.

### To Reproduce

Experiments have been executed in order to study PPO:

![Captura de pantalla de 2022-04-21 11-11-08](https://user-images.githubusercontent.com/23475034/164421838-fddb811b-c1ba-4f79-aceb-3712ce113879.png)

That is the percentage extracted by Sinergym Logger, whose metric is calculated using directly comfort penalty (`=! 0`):

![Captura de pantalla de 2022-04-21 11-11-19](https://user-images.githubusercontent.com/23475034/164421851-2c36a44f-643b-4d9e-8c86-c8569485b788.png)

That is the internal temperature in the building during an episode. According to that graph, comfort penalty should be 0.

![Captura de pantalla de 2022-04-21 11-12-58](https://user-images.githubusercontent.com/23475034/164421950-1dc105fe-83e3-4ffe-bce7-4fb3d29b54d4.png)

However, this does not correspond to reality as we can see in the last image shown.

### Expected behavior

According to the graphs shown, it should never have a comfort penalty and a comfort violation rate of 0%.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/jajimer/sinergym/issues) in the repo (**required**)
- [x] I have read the [documentation](https://jajimer.github.io/sinergym/build/html/index.html) (**required**)

:pencil: Please, don't forget to include more labels besides `bug` if it is necessary.

**Comment by manjavacas** [comment]
This problem has been proven only in `Datacenter` experiments. A possible cause may be that some default (and incorrect) values in the definition of the `LinearReward` function are being used.

![imagen](https://user-images.githubusercontent.com/40355800/164434406-2f6ddf9a-a315-4951-abbb-a4b25a035b1a.png)

Maybe an _ad hoc_ definition of `LinearReward` is necessary for this environment? (i.e. taking two temperature variables)
