### ISSUE TITLE
BUG: Shutdown vm from python script doesn't work

### ISSUE THREAD

**Issue by AlejandroCN7** [jajimer/sinergym#89]
Currently, my code is:

`if args.remote_store: os.system('shutdown now -h')`

This code is executed when script in remote machine ends, but i have the next error modifying gcloud API to see output in terminal:

`sh: 1: shutdown: not found`

**Comment by AlejandroCN7** [comment]
I have tried too: `os.system('sudo shutdown now -h')` but doesn't work.

**Comment by AlejandroCN7** [comment]
@MrLutik I have tried that command too, but I have `sh: 1: systemctl: not found`. Anyway, thank you very much for the help :)

**Comment by AlejandroCN7** [comment]
I have though about a detail. Actually, there is a **container** executing a python script inner **Google Cloud VM**. Then, shutting down should do it from **vm host** and not from **container script**.

I have to look into how to execute shutting down from container to host, maybe ssh connection?

**Comment by miguems** [comment]
I've just seen a similar answer in SO: https://stackoverflow.com/questions/52748332/how-to-make-gce-instance-stop-when-its-deployed-container-finishes/58215421#58215421. worth checking
