### ISSUE TITLE
NORMALIZATION RANGES for the 2ZoneDataCenterHVAC_wEconomizer_NY.idf building seem to be missing

### ISSUE THREAD

**Issue by VoyagerXX** [jajimer/sinergym#92]
When I was trying to run the DRL_Usage.py script with the Eplus-datacenter-mixed-continuous-v1 environment, I got the following error:

`KeyError Traceback (most recent call last)
/tmp/ipykernel_2958/1612162543.py in <module>
125
126 # Training
--> 127 model.learn(total_timesteps=timesteps, callback=callback, log_interval=1)
128 # model.save(name)
129

~/miniconda3/lib/python3.8/site-packages/stable_baselines3/sac/sac.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps)
289 ) -> OffPolicyAlgorithm:
290
--> 291 return super(SAC, self).learn(
292 total_timesteps=total_timesteps,
293 callback=callback,

~/miniconda3/lib/python3.8/site-packages/stable_baselines3/common/off_policy_algorithm.py in learn(self, total_timesteps, callback, log_interval, eval_env, eval_freq, n_eval_episodes, tb_log_name, eval_log_path, reset_num_timesteps)
336 ) -> "OffPolicyAlgorithm":
337
--> 338 total_timesteps, callback = self._setup_learn(
339 total_timesteps,
340 eval_env,

~/miniconda3/lib/python3.8/site-packages/stable_baselines3/common/off_policy_algorithm.py in _setup_learn(self, total_timesteps, eval_env, callback, eval_freq, n_eval_episodes, log_path, reset_num_timesteps, tb_log_name)
312 replay_buffer.dones[pos] = True
313
--> 314 return super()._setup_learn(
315 total_timesteps,
316 eval_env,

~/miniconda3/lib/python3.8/site-packages/stable_baselines3/common/base_class.py in _setup_learn(self, total_timesteps, eval_env, callback, eval_freq, n_eval_episodes, log_path, reset_num_timesteps, tb_log_name)
424 # Avoid resetting the environment when calling ``.learn()`` consecutive times
425 if reset_num_timesteps or self._last_obs is None:
--> 426 self._last_obs = self.env.reset() # pytype: disable=annotation-type-mismatch
427 self._last_episode_starts = np.ones((self.env.num_envs,), dtype=bool)
428 # Retrieve unnormalized observation for saving into the buffer

~/miniconda3/lib/python3.8/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py in reset(self)
59 def reset(self) -> VecEnvObs:
60 for env_idx in range(self.num_envs):
---> 61 obs = self.envs[env_idx].reset()
62 self._save_obs(env_idx, obs)
63 return self._obs_from_buf()

~/miniconda3/lib/python3.8/site-packages/stable_baselines3/common/monitor.py in reset(self, **kwargs)
77 raise ValueError(f"Expected you to pass keyword argument {key} into reset")
78 self.current_reset_info[key] = value
---> 79 return self.env.reset(**kwargs)
80
81 def step(self, action: Union[np.ndarray, int]) -> GymStepReturn:

~/miniconda3/lib/python3.8/site-packages/gym/core.py in reset(self, **kwargs)
318 def reset(self, **kwargs):
319 observation = self.env.reset(**kwargs)
--> 320 return self.observation(observation)
321
322 def step(self, action):

~/sinergym/sinergym/utils/wrappers.py in observation(self, obs)
39 for i, variable in enumerate(self.env.variables['observation']):
40 # normalization
---> 41 obs[i] = (obs[i] - self.ranges[variable][0]) / \
42 (self.ranges[variable][1] - self.ranges[variable][0])
43 # If value is out

KeyError: 'Zone Thermostat Heating Setpoint Temperature (West Zone)'`

I think this is caused by the fact that the https://github.com/jajimer/sinergym/blob/main/sinergym/utils/common.py file does not contain NORMALIZATION RANGES for the DataCenter.  

Can you please add this info as soon as possible?
Thank you.

**Comment by AlejandroCN7** [comment]
This bug has been solved. *DRL_usage.py* has been updated similar to *DRL_battery.py* but without gcloud functionality in order to use it easily and more configurable.
