### ISSUE TITLE
Missing data in NORMALIZATION RANGES for the Datacenter

### ISSUE THREAD

**Issue by VoyagerXX** [jajimer/sinergym#96]
Hi,
Thank you very much for updating Sinergym to version 1.4.0, and for adding the NORMALIZATION RANGES for the Datacenter (as I had requested).

However, when I ran the code, I found that RANGES_DATACENTER was missing data for two items:
'Zone Thermal Comfort Clothing Value (East Zone PEOPLE)': [0.0, 0.0],
'Zone Thermal Comfort Clothing Value (West Zone PEOPLE)': [0.0, 0.0],

This causes a "divide by zero" error during normalization.

I added in the following data:
'Zone Thermal Comfort Clothing Value (East Zone PEOPLE)': [0.5, 1.0],
'Zone Thermal Comfort Clothing Value (West Zone PEOPLE)': [0.5, 1.0],

Are these values appropriate?  Can you please tell me where the Normalization Ranges data for the Datacenter come from?

Thank you very much for all your help.

**Comment by AlejandroCN7** [comment]
Let me take a look. Thank you so much for information.

**Comment by AlejandroCN7** [comment]
@VoyagerXX this data come from a function called `ranges_getter` in `sinergym/utils/common.py`. This function uses outputs from executions examples and built this dictionary with absolute maximum and minimum. If there is some bug in code, I recommend you to execute several examples and look what is that maximum and minimum using `monitor.csv` from sinergym logger. Meanwhile, I am going to look into if there is some problem with those variables in datacenter.

**Comment by AlejandroCN7** [comment]
It seems these variables are always 0.0 in datacenter environments. In any case, ranges [0.0 - 0.0] is an exception not caught in our code. I will tag this issue with bug label and solve it. Thank you so much for your report :)
