### ISSUE TITLE
API Reference Section in Github Pages documentation doesn't work correctly

### ISSUE THREAD

**Issue by AlejandroCN7** [jajimer/sinergym#98]
This documentation section works correctly in local compilation. I think the problem is in Github Action for remote documentation compilation and update due to the next:
![Captura](https://user-images.githubusercontent.com/23475034/143912033-c93e8ff5-e70b-4d4b-9369-2647c3bac6af.PNG)
Maybe trying to specify these module dependencies in that action (I don't know how yet) could be work successfully.

**Comment by miguems** [comment]
maybe something related with the paths in that machine? or a missing pip install? I would suggest you try to replicate the compilation inside an empty docker environment and see if it goes through...
